"""Hexapod Link entry point.

Builds the Dash app and serves it with waitress on a loopback-only port, inside
a pywebview window by default.

    python hexapod_link.py              # native window
    python hexapod_link.py --no-window  # serve only, open the URL in a browser
"""

import argparse
import mimetypes
import os
import socket
import sys
import threading
import time

import waitress
from dash import Dash, html

from hexapod.preferences import load_layout, load_theme
from hexapod.robot_link import ROBOT_LINK
from pages.drive import register_drive_route
from pages.shell import make_topbar
from pages.workspace import WORKSPACE
from style_settings import EXTERNAL_STYLESHEETS
from texts import APP_TITLE


# ....................
# Dash app
# ....................


def resource_root():
    """Directory holding the bundled data files (assets/, ...).

    A PyInstaller one-file build unpacks itself into a temporary directory and
    points sys._MEIPASS at it; __file__ then refers to a path inside the frozen
    archive and cannot be used to locate assets. Outside a bundle this is just
    the repository root.
    """
    return getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)))


ASSETS_PATH = os.path.join(resource_root(), "assets")

# Windows has no registry entry for .woff2, so the bundled fonts would be
# served as application/octet-stream.
mimetypes.add_type("font/woff2", ".woff2")


# The saved workspace sizes, by preference key, and the CSS variable each sets
# (WORKSPACE in assets/industrial.css).
LAYOUT_VARIABLES = {
    "dock_h": "--dock-h",
    "lib_w": "--lib-w",
    "run_w": "--run-w",
}


class HexapodDash(Dash):
    """Dash, with the saved colour theme and workspace sizes written into the
    served page.

    Both live on the <html> element, which Dash's layout cannot reach; setting
    them from a callback would only happen after the first paint, so a dark
    start would flash light and a resized dock would jump. Putting them into
    the index page itself avoids that. See the theme and workspace sections of
    pages/shell.py.
    """

    def interpolate_index(self, **kwargs):
        index = super().interpolate_index(**kwargs)
        theme = load_theme()
        sizes = "; ".join(
            f"{LAYOUT_VARIABLES[key]}: {px}px" for key, px in load_layout().items() if px
        )
        style = f' style="{sizes}"' if sizes else ""
        return index.replace(
            "<html>", f'<html data-theme="{theme}" data-bs-theme="{theme}"{style}>', 1
        )


app = HexapodDash(
    __name__,
    assets_folder=ASSETS_PATH,
    external_stylesheets=EXTERNAL_STYLESHEETS,
    suppress_callback_exceptions=True,
    title=APP_TITLE,
)
server = app.server
register_drive_route(server)


# ....................
# Layout
# ....................


def serve_layout():
    """Built per page load, so the top bar's theme button matches the saved
    theme (see HexapodDash above). There is one screen, served at any path."""
    return html.Div([make_topbar(load_theme()), WORKSPACE], className="app-shell")


app.layout = serve_layout


# ....................
# Server and window
# ....................

HOST = "127.0.0.1"

# How long to wait for waitress to start accepting connections before giving
# up. Generous: the first import of plotly/dash is slow on a cold filesystem.
STARTUP_TIMEOUT = 30.0

WINDOW_WIDTH = 1440
WINDOW_HEIGHT = 900
WINDOW_MIN_SIZE = (1024, 700)

# Windows draws the window icon through System.Drawing.Icon, which reads real
# ICO files only; the GTK, Qt and Cocoa backends all take the PNG. Both files
# are generated by tools/make_icon.py.
WINDOW_ICON_FILE = "app.ico" if sys.platform == "win32" else "icon.png"


def window_icon():
    """Absolute path to the window icon, or None if it is not there.

    Without this the window borrows whatever icon the running executable has:
    the Python interpreter's when started with `python hexapod_link.py`, and on
    Linux nothing at all, since only the Windows build embeds one in the
    binary. Returning None is what pywebview expects when there is no icon.
    """
    path = os.path.join(ASSETS_PATH, WINDOW_ICON_FILE)
    return path if os.path.isfile(path) else None


def find_free_port():
    """Ask the OS for an unused loopback port."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.bind((HOST, 0))
        return probe.getsockname()[1]


def wait_until_serving(port, timeout=STARTUP_TIMEOUT):
    """Block until the server accepts a connection, or the timeout expires."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with socket.create_connection((HOST, port), timeout=0.5):
                return True
        except OSError:
            time.sleep(0.05)
    return False


def start_server(port=None):
    """Start the WSGI server on a daemon thread and return its URL.

    Binding to 127.0.0.1 rather than 0.0.0.0 keeps the app off the network and
    avoids the Windows Firewall prompt on first launch. It does not affect the
    robot link, which is a separate outbound UDP socket.
    """
    port = port or find_free_port()

    # threads=8 is well above what a single window needs, but Dash fires
    # several callbacks concurrently on a page load and a starved pool shows up
    # as a visibly slow UI. Nothing external ever sees this server, so ident=None
    # drops the Server header.
    thread = threading.Thread(
        target=waitress.serve,
        args=(server,),
        kwargs={"host": HOST, "port": port, "threads": 8, "ident": None},
        name="hexapod-wsgi",
        daemon=True,
    )
    thread.start()

    if not wait_until_serving(port):
        # The thread is a daemon, so there is nothing to clean up; if waitress
        # failed to bind, the traceback has already gone to stderr.
        raise RuntimeError(
            f"server did not come up on {HOST}:{port} within {STARTUP_TIMEOUT:.0f}s"
        )

    return f"http://{HOST}:{port}"


def shutdown_robot_link():
    """Return the robot to LUT control before the process goes away.

    The streaming thread is a daemon and would simply die with the process,
    leaving the robot holding the last streamed pose until the firmware's
    1000 ms real-time timeout fires. disconnect() sends RT_EXIT explicitly and
    is a no-op when nothing is connected.
    """
    try:
        ROBOT_LINK.disconnect()
    except Exception as error:  # never block the window from closing
        print(f"robot link shutdown failed: {error}", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description="Run Hexapod Link.")
    parser.add_argument(
        "--port",
        type=int,
        default=None,
        help="serve on this port instead of an OS-assigned one",
    )
    parser.add_argument(
        "--no-window",
        action="store_true",
        help="start the server only and print its URL, without opening a window",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="open the webview's developer tools",
    )
    args = parser.parse_args()

    url = start_server(args.port)

    if args.no_window:
        print(f"serving on {url} (ctrl-c to stop)")
        try:
            threading.Event().wait()
        except KeyboardInterrupt:
            pass
        finally:
            shutdown_robot_link()
        return

    # Imported here so the app can be served (or imported by tests and tools)
    # without pywebview installed.
    import webview

    window = webview.create_window(
        APP_TITLE,
        url,
        width=WINDOW_WIDTH,
        height=WINDOW_HEIGHT,
        min_size=WINDOW_MIN_SIZE,
        text_select=True,
    )
    # 'closing' fires while the window and the server thread are both still
    # alive, so the RT_EXIT packet actually makes it out. Returning None lets
    # the close proceed.
    window.events.closing += shutdown_robot_link

    webview.start(debug=args.debug, icon=window_icon())


if __name__ == "__main__":
    main()
