# PyInstaller build spec for the standalone desktop app.
#
#   pyinstaller hexapod.spec
#
# Produces dist/HexapodLink/HexapodLink[.exe] (a one-folder build). Set ONEFILE
# below for a single self-extracting executable instead; that is tidier to hand
# out but adds several seconds to every launch, because the whole bundle is
# unpacked to a temporary directory each time it starts.
#
# Builds on Windows and Linux. The difference between them is which GUI backend
# pywebview resolves at runtime, which decides both what has to be forced into
# the bundle and what has to be kept out of it -- see WINDOWS below.

import sys

from PyInstaller.utils.hooks import collect_data_files, copy_metadata

ONEFILE = False

APP_NAME = "HexapodLink"

WINDOWS = sys.platform == "win32"

# assets/app.ico and assets/favicon.ico are both real multi-resolution ICOs
# (16-256 px), generated by tools/make_icon.py.
#
# Only Windows embeds an icon in the executable; on Linux the icon belongs to
# the .desktop entry, and handing PyInstaller an .ico there just warns.
ICON = "assets/app.ico" if WINDOWS else None

# The app's own static files: stylesheets, the bundled fonts and the favicon.
# app.py locates these at runtime through sys._MEIPASS.
datas = [("assets", "assets")]

# Dash and its component libraries ship JavaScript bundles alongside a
# package.json that Dash reads at import time to work out which files to serve.
# PyInstaller's analysis only follows Python imports, so the data files and the
# dist-info metadata (Dash checks component package versions) must be collected
# explicitly or the app starts to a blank window.
for package in ("dash", "dash_daq", "dash_bootstrap_components", "plotly"):
    datas += collect_data_files(package)
    datas += copy_metadata(package)

# Imported dynamically rather than by name, so the analysis misses them.
hiddenimports = [
    # waitress resolves its server class through a string.
    "waitress",
]

# pywebview picks a GUI backend at runtime, so nothing imports these by name.
if WINDOWS:
    # EdgeChromium through winforms, via pythonnet.
    hiddenimports += ["webview.platforms.winforms", "clr_loader"]
else:
    # GTK/WebKit2 through PyGObject. `gi` is a system package with typelibs
    # alongside it, so the runner needs gir1.2-webkit2 installed as well.
    hiddenimports += ["webview.platforms.gtk", "gi"]

# Nothing in the app imports these, but PyInstaller follows optional-import
# branches inside its dependencies and will happily bundle whatever it finds
# installed. Left unexcluded in a rich environment this build comes out around
# 1 GB, most of it polars, pyarrow and PySide6.
#
# Build from a minimal environment as well (see the header of this file); the
# excludes are a backstop, not a substitute.
#
# That environment also has to be based on a python.org (or system) Python, not
# on a conda one. Conda's extension modules resolve their DLLs out of
# <env>\Library\bin, a layout the bundle does not reproduce, so a build made
# from a conda-based venv collects libssl/libcrypto that its own _ssl.pyd then
# refuses: "DLL load failed while importing _ssl: The specified procedure could
# not be found", at the first import of ssl. The size is right and the build
# reports success -- only running it shows the problem, which is what the smoke
# test step in .github/workflows/build-desktop.yml is there to do.
excludes = [
    # plotly 6 talks to dataframes through narwhals, which probes every
    # dataframe library it knows about. None of them are used here: the figures
    # are built from plain dicts and numpy arrays.
    "polars",
    "pyarrow",
    "pandas",
    "duckdb",
    "modin",
    "cudf",
    "dask",
    "ibis",
    "sqlframe",
    "pyspark",
    "vaex",
    # pywebview supports several GUI backends and imports whichever are
    # available. Only the Qt ones are unwanted on both platforms; `gi` is the
    # backend itself on Linux and is excluded below on Windows only.
    "PySide6",
    "PySide2",
    "PyQt5",
    "PyQt6",
    # Dash imports IPython for its Jupyter integration, which drags in the
    # whole interactive stack.
    "IPython",
    "ipykernel",
    "jedi",
    "jupyter",
    "notebook",
    # Miscellaneous heavyweights reachable from the above.
    "scipy",
    "matplotlib",
    "PIL",
    "tkinter",
    "sphinx",
    "babel",
    "Cython",
    # Development tooling.
    "pytest",
    "flake8",
    "pylint",
    "astroid",
    "isort",
]

if WINDOWS:
    # Nothing on Windows uses PyGObject, and a stray copy would be bundled.
    excludes.append("gi")

# Unblock the bundled managed assemblies before anything tries to load them --
# without this, a bundle extracted from a downloaded .zip opens no window at
# all. See rthook_clear_motw.py. A no-op for a bundle that was never
# downloaded, and Windows-only: the Linux backend involves no .NET.
runtime_hooks = ["rthook_clear_motw.py"] if WINDOWS else []

a = Analysis(
    ["desktop.py"],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=runtime_hooks,
    excludes=excludes,
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

if ONEFILE:
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.datas,
        [],
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        runtime_tmpdir=None,
        # No console window; desktop.py writes nothing to stdout in normal use.
        console=False,
        disable_windowed_traceback=False,
        icon=ICON,
    )
else:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        console=False,
        disable_windowed_traceback=False,
        icon=ICON,
    )

    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=False,
        name=APP_NAME,
    )
