# Real-time link between the simulator and the physical ESP32 hexapod.
#
# The simulator and the robot describe a leg pose with different conventions.
# The simulator uses alpha/beta/gamma (see hexapod/linkage.py); the robot's
# firmware stores raw servo ticks generated by path_tool's inverse_kinematics,
# which produces servo angles j1/j2/j3 in the range [0, 180] where 90 is the
# servo's mid position.
#
# The relationship, verified against path_tool by round-tripping foot-tip
# positions, is:
#
#     j1 = 90 + alpha
#     j2 = 90 - sign * beta
#     j3 = 90 + sign * gamma
#
# where `sign` is the leg's legScale from the robot's config, i.e. how that leg's
# femur and tibia servos are mirrored. Mochi and Macaroon mirror the left side
# (+1 right, -1 left); Nougat mirrors legs 0, 4 and 5. A servo angle becomes a
# tick with
#
#     ticks = round(j / 180 * (SERVO_MAX - SERVO_MIN) + SERVO_MIN)
#
# which maps j=90 to 307, matching SERVOMID in the firmware's config.h.
#
# Only the angle convention differs. Leg indices and joint indices are shared
# with the firmware -- see hexapod/naming.py -- so nothing is reordered here.
#
# The robot's config -- geometry, servo range, frame delay, speed limits and
# command list -- is read from the robot itself when connecting; see
# hexapod/robot_config.py. The firmware version is asked for over UDP at the
# same time, which also shows that the robot hears the motion channel.

import socket
import struct
import threading
import time

from settings import (
    ROBOT_DEFAULT_IP,
    ROBOT_UDP_PORT,
    ROBOT_STREAM_HZ,
    ROBOT_PING_HZ,
    ROBOT_DRIVE_HOLD_S,
    ROBOT_DEFAULT_MAX_STEP,
    ROBOT_SEQUENCE_MAX_STEP,
    ROBOT_VERSION_TIMEOUT_S,
    ROBOT_VERSION_ATTEMPTS,
)
from hexapod import robot_http
from hexapod.robot_config import (
    GENERIC_CONFIG,
    RobotConfigError,
    clamp_speed,
    command_id,
    fetch_robot_config,
    get_joint_limits,
    get_leg_signs,
    get_sequence_fps,
    load_startup_config,
    save_cached_config,
)
from hexapod.robot_http import RobotHttpError, split_address

# Packet magics, mirrors protocol.h in the firmware
MAGIC_MOTION = 0xA5
MAGIC_POSE = 0xA6
MAGIC_SESSION = 0xA7
MAGIC_VERSION = 0xA8

POSE_FLAG_SNAP = 0x01

# Session actions
RT_EXIT = 0
RT_ENTER = 1
RT_RELAX = 2
RT_PING = 3

# struct formats. '<' keeps these little-endian and unpadded, matching the
# firmware's #pragma pack(1) structs (7 / 44 / 6 bytes). The motion packet is
# the 7-byte form that carries the gait playback speed.
_FMT_MOTION = "<BBIB"
_FMT_POSE = "<BBHI" + "h" * 18
_FMT_SESSION = "<BBI"
# Version query (5 bytes) and the fixed head of its reply (9 bytes); the build
# tag follows the reply's head as UTF-8, running to the end of the datagram.
_FMT_VERSION_REQUEST = "<BI"
_FMT_VERSION_REPLY = "<BIBBBB"


def parse_version_reply(data, seq):
    """Decode the robot's answer to version query `seq`.

    Returns {"version": "MAJOR.MINOR.PATCH", "build", "protocol"}, or None when
    `data` is not that answer.
    """
    head = struct.calcsize(_FMT_VERSION_REPLY)
    if len(data) < head or data[0] != MAGIC_VERSION:
        return None
    _, reply_seq, protocol, major, minor, patch = struct.unpack_from(
        _FMT_VERSION_REPLY, data
    )
    if reply_seq != seq:
        return None
    return {
        "version": f"{major}.{minor}.{patch}",
        "build": data[head:].decode("utf-8", errors="replace"),
        "protocol": protocol,
    }


def joint_angles_to_servo_angles(leg_sign, coxia, femur, tibia):
    """Convert one leg's simulator angles to the robot's j1/j2/j3 servo angles."""
    return (
        90.0 + coxia,
        90.0 - leg_sign * femur,
        90.0 + leg_sign * tibia,
    )


def servo_angle_to_ticks(angle, servo_min=102, servo_max=512):
    """Convert a servo angle in degrees to a PWM tick count, clamped to range."""
    ticks = round(angle * (servo_max - servo_min) / 180.0 + servo_min)
    return int(min(max(ticks, servo_min), servo_max))


def clamp_pose_angles(coxia, femur, tibia, robot_config=GENERIC_CONFIG):
    """Clamp simulator angles to the robot's mechanically safe joint range.

    The simulator permits far more travel than the hardware has (beta and gamma
    go to +/-180 there), so this is what keeps an unreachable simulator pose
    from being sent to the servos as a hard stop.
    """
    limits = get_joint_limits(robot_config)
    return (
        min(max(coxia, -limits["coxia"]), limits["coxia"]),
        min(max(femur, -limits["femur"]), limits["femur"]),
        min(max(tibia, -limits["tibia"]), limits["tibia"]),
    )


def pose_to_ticks(poses, robot_config=GENERIC_CONFIG):
    """Convert a simulator pose dict to a flat list of 18 servo ticks.

    `poses` is the structure used throughout the simulator: keys 0-5 (int or
    str) mapping to dicts with "coxia", "femur" and "tibia" in degrees.
    Returns ticks ordered leg-major, matching the firmware's LUT layout.
    """
    signs = get_leg_signs(robot_config)
    servo_min = robot_config["servo_min"]
    servo_max = robot_config["servo_max"]

    ticks = []
    for leg_id in range(6):
        pose = poses.get(leg_id, poses.get(str(leg_id)))
        if pose is None:
            coxia = femur = tibia = 0.0
        else:
            coxia = pose.get("coxia") or 0.0
            femur = pose.get("femur") or 0.0
            tibia = pose.get("tibia") or 0.0

        coxia, femur, tibia = clamp_pose_angles(coxia, femur, tibia, robot_config)
        for angle in joint_angles_to_servo_angles(signs[leg_id], coxia, femur, tibia):
            ticks.append(servo_angle_to_ticks(angle, servo_min, servo_max))

    return ticks


# Standby posture, decoded from the firmware's lut_standby ({307, 239, 273} on an
# unmirrored leg). Every robot bakes standby from gen_posture(60, 75), whose
# joint angles do not depend on link lengths, so this is shared; only the
# mirroring differs, and pose_to_ticks applies that.
STANDBY_POSE = {
    leg_id: {
        "id": leg_id,
        "coxia": 0.0,
        "femur": 30.0,
        "tibia": -15.0,
    }
    for leg_id in range(6)
}


class RobotLink:
    """UDP client that streams simulator poses to the hexapod.

    A background thread republishes the most recent pose at a steady rate. That
    matters because Dash only runs callbacks when the user interacts, while the
    firmware drops out of real-time mode if it stops hearing from us. The thread
    keeps the session alive and turns sporadic UI events into a smooth stream.
    """

    def __init__(self, robot_config=None, udp_port=ROBOT_UDP_PORT):
        self._lock = threading.Lock()
        self._udp_port = udp_port
        self._socket = None
        self._thread = None
        self._stop_event = threading.Event()

        robot_config = robot_config or load_startup_config()
        self._robot_config = robot_config
        self._config_version = 0
        self._ip = ROBOT_DEFAULT_IP
        self._connected = False
        self._firmware = None
        self._streaming = False
        self._max_step = ROBOT_DEFAULT_MAX_STEP
        self._speed_pct = robot_config["speed"]["default"]
        self._ticks = pose_to_ticks(STANDBY_POSE, robot_config)
        self._seq = 0
        self._packets_sent = 0
        self._last_error = None

        # Gait sequence playback, driven by the stream thread
        self._sequence = None
        self._sequence_index = 0
        self._sequence_loop = True
        self._sequence_next_time = 0.0
        self._sequence_fps_override = None
        self._sequence_fps = get_sequence_fps(robot_config, self._speed_pct)

        # The gait the controller is holding the robot in, and when the hold
        # runs out unless it is renewed (see drive()).
        self._drive_motion = None
        self._drive_deadline = None

    # ---------------------------------------------------------------- status

    @property
    def connected(self):
        with self._lock:
            return self._connected

    @property
    def streaming(self):
        with self._lock:
            return self._streaming

    @property
    def robot_config(self):
        """The config of the robot being modelled: connected, cached or generic."""
        with self._lock:
            return self._robot_config

    @property
    def config_version(self):
        """Bumped whenever a robot's config is loaded, so the UI can follow."""
        with self._lock:
            return self._config_version

    @property
    def ip(self):
        with self._lock:
            return self._ip

    @property
    def firmware(self):
        """The connected robot's {"version", "build", "protocol"}, else None."""
        with self._lock:
            return self._firmware

    @property
    def speed_pct(self):
        with self._lock:
            return self._speed_pct

    def status(self):
        with self._lock:
            return {
                "connected": self._connected,
                "streaming": self._streaming,
                "ip": self._ip,
                "packets_sent": self._packets_sent,
                "last_error": self._last_error,
                "max_step": self._max_step,
                "speed_pct": self._speed_pct,
                "robot_name": self._robot_config["name"],
                "robot_label": self._robot_config["label"],
                "config_source": self._robot_config["source"],
                "config_version": self._config_version,
                "firmware": self._firmware,
            }

    # ------------------------------------------------------------ connection

    def connect(self, ip=None):
        """Read the robot's config, then open the socket and enter real-time mode.

        The config comes first: the robot's geometry decides how every pose is
        turned into servo ticks, so nothing is sent until it is known. A robot
        that does not answer leaves the link disconnected with the reason in
        `last_error`.
        """
        ip = (ip or self.ip or ROBOT_DEFAULT_IP).strip()
        try:
            robot_config = fetch_robot_config(ip)
        except RobotConfigError as error:
            with self._lock:
                self._ip = ip
                self._last_error = str(error)
            return False

        save_cached_config(robot_config)
        self._load_config(robot_config)

        # /robot_config carries the version too, so an unanswered query still
        # leaves something to show; it only means the UDP side is unconfirmed.
        firmware = self.query_firmware(ip) or robot_config["firmware"]

        with self._lock:
            self._ip = ip
            self._firmware = firmware
            if self._socket is None:
                try:
                    self._socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                    self._socket.setblocking(False)
                except OSError as error:
                    self._last_error = str(error)
                    return False
            self._connected = True
            self._last_error = None

        self._send_session(RT_ENTER)
        self._start_thread()
        return True

    def query_firmware(self, ip=None):
        """Ask the robot for its firmware version over UDP.

        Returns what parse_version_reply() decodes, or None if no answer came.
        The query has a socket of its own: the streaming socket never reads, and
        the reply would only queue up on it. The firmware does not count the
        query as control input, so it neither feeds nor trips the failsafe.
        """
        host, _ = split_address(ip or self.ip)
        with self._lock:
            self._seq += 1
            seq = self._seq
        request = struct.pack(_FMT_VERSION_REQUEST, MAGIC_VERSION, seq)

        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        except OSError:
            return None

        with sock:
            for _ in range(ROBOT_VERSION_ATTEMPTS):
                deadline = time.monotonic() + ROBOT_VERSION_TIMEOUT_S
                try:
                    sock.sendto(request, (host, self._udp_port))
                    # Skip anything that is not the answer, e.g. a late reply
                    # to an earlier query.
                    while (remaining := deadline - time.monotonic()) > 0:
                        sock.settimeout(remaining)
                        data, _ = sock.recvfrom(512)
                        reply = parse_version_reply(data, seq)
                        if reply is not None:
                            return reply
                except socket.timeout:
                    continue
                except OSError:
                    # Unreachable; Windows also reports a closed port this way.
                    return None
        return None

    def _load_config(self, robot_config):
        """Switch the link to a newly read robot config."""
        with self._lock:
            self._robot_config = robot_config
            self._config_version += 1
            # The robot's own speed is what its native gaits are playing at.
            self._speed_pct = clamp_speed(
                robot_config, robot_config["speed"].get("current", self._speed_pct)
            )
            self._sequence = None
            self._sequence_index = 0
            self._sequence_fps_override = None
            self._sequence_fps = get_sequence_fps(robot_config, self._speed_pct)
            self._ticks = pose_to_ticks(STANDBY_POSE, robot_config)

    def disconnect(self):
        """Return the robot to LUT control and close the socket."""
        self._send_session(RT_EXIT)
        self._stop_thread()

        with self._lock:
            self._connected = False
            self._firmware = None
            self._streaming = False
            self._sequence = None
            self._sequence_index = 0
            self._drive_motion = None
            self._drive_deadline = None
            if self._socket is not None:
                self._socket.close()
                self._socket = None

    def set_max_step(self, max_step):
        with self._lock:
            self._max_step = max(1, int(max_step))

    def set_streaming(self, streaming):
        with self._lock:
            self._streaming = bool(streaming) and self._connected

    def set_motion_speed(self, pct):
        """Set how fast gaits play, in percent of the robot's tuned frame rate.

        Applies to the robot's own gaits -- sent to it now, and with every
        motion command after -- and to gaits streamed from the simulator, whose
        frame rate is scaled to match. Returns the speed that was applied.
        """
        with self._lock:
            pct = clamp_speed(self._robot_config, pct)
            self._speed_pct = pct
            if self._sequence_fps_override is None:
                self._sequence_fps = get_sequence_fps(self._robot_config, pct)
            connected = self._connected
            ip = self._ip

        if connected:
            try:
                robot_http.set_speed(ip, pct)
            except RobotHttpError as error:
                # Not fatal: the next motion command carries the speed anyway.
                with self._lock:
                    self._last_error = f"Speed not applied: {error}"
        return pct

    # --------------------------------------------------------------- sending

    def send_pose(self, poses, snap=False):
        """Set the pose that will be streamed to the robot.

        Posing by hand takes precedence over any gait sequence in flight.
        """
        ticks = pose_to_ticks(poses, self.robot_config)
        with self._lock:
            self._ticks = ticks
            self._sequence = None
            self._sequence_index = 0
            self._drive_motion = None
            self._drive_deadline = None
        if self.streaming:
            self._send_pose_packet(snap=snap)

    def send_motion_command(self, motion_name):
        """Ask the robot to run one of its own built-in gait LUTs.

        Preferred over streaming for the pre-programmed motions: the ESP32 plays
        the gait from flash, so smoothness does not depend on WiFi latency.
        """
        motion_id = command_id(self.robot_config, motion_name)
        if motion_id is None:
            return False

        # Streaming and LUT playback are mutually exclusive on the robot: the
        # firmware leaves real-time mode as soon as it sees a motion command.
        with self._lock:
            self._streaming = False
            self._sequence = None
            self._sequence_index = 0
            self._drive_motion = None
            self._drive_deadline = None
            self._seq += 1
            seq = self._seq
            speed = self._speed_pct
        return self._send(struct.pack(_FMT_MOTION, MAGIC_MOTION, motion_id, seq, speed))

    def drive(self, motion_name):
        """Run one of the robot's own gaits for as long as it is held.

        The controller over the view calls this again and again while a pad is
        held, and with "standby" when it is let go. Only a change of gait is
        sent to the robot; a repeat just renews the hold. If the calls stop
        without a standby, the stream thread sends one ROBOT_DRIVE_HOLD_S after
        the last (_expire_drive). Returns False for a motion the robot does
        not have, or when it could not be sent.
        """
        deadline = time.monotonic() + ROBOT_DRIVE_HOLD_S
        with self._lock:
            if motion_name == self._drive_motion:
                self._drive_deadline = deadline
                return True

        if not self.send_motion_command(motion_name):
            return False
        if motion_name != "standby":
            with self._lock:
                self._drive_motion = motion_name
                self._drive_deadline = deadline
        return True

    def _expire_drive(self):
        """Send the robot to standby if the controller's hold has run out."""
        with self._lock:
            expired = self._drive_deadline is not None and time.monotonic() > self._drive_deadline
        if expired:
            self.send_motion_command("standby")

    def play_sequence(self, pose_frames, loop=True, fps=None):
        """Stream a list of poses as a gait, timed by the stream thread.

        Driving frames from Dash callbacks would tie gait timing to browser
        round-trips; doing it here keeps the cadence steady. Prefer
        send_motion_command() for the robot's built-in gaits, which avoids the
        network being in the loop at all.

        Without an explicit `fps` the frames play at the rate the robot would
        play its own LUT at the current speed.
        """
        robot_config = self.robot_config
        frames = [pose_to_ticks(pose, robot_config) for pose in pose_frames]
        if not frames:
            return False

        with self._lock:
            self._drive_motion = None
            self._drive_deadline = None
            self._sequence = frames
            self._sequence_index = 0
            self._sequence_loop = loop
            self._sequence_fps_override = fps
            self._sequence_fps = fps or get_sequence_fps(robot_config, self._speed_pct)
            self._sequence_next_time = 0.0
            self._streaming = self._connected
        return True

    def stop_sequence(self):
        """Stop gait playback and hold the last frame."""
        with self._lock:
            self._sequence = None
            self._sequence_index = 0

    def _advance_sequence(self):
        """Return the frame that is due now, else None.

        If the thread woke late (Windows timer granularity is ~15 ms, coarser
        than a 12 ms gait frame) this skips the frames that fell due in the
        meantime rather than emitting them all late, so the gait keeps correct
        wall-clock timing instead of drifting slower and slower.
        """
        now = time.monotonic()
        with self._lock:
            if not self._sequence:
                return None

            if now < self._sequence_next_time:
                return None

            frame_period = 1.0 / self._sequence_fps

            if self._sequence_next_time == 0.0:
                # First frame of a new sequence.
                self._sequence_next_time = now
                overdue = 1
            else:
                overdue = int((now - self._sequence_next_time) / frame_period) + 1

            frame = None
            for _ in range(overdue):
                frame = self._sequence[self._sequence_index]
                self._sequence_index += 1

                if self._sequence_index >= len(self._sequence):
                    if self._sequence_loop:
                        self._sequence_index = 0
                    else:
                        self._sequence = None
                        self._sequence_index = 0
                        break

            # Advance the schedule by whole frame periods from when the frame
            # was *due*, not from when this thread happened to wake. Resetting
            # from `now` would fold the wake-up lateness into every frame and
            # the gait would run progressively slower than on the robot.
            self._sequence_next_time += overdue * frame_period
            if self._sequence_next_time <= now:
                # Fell far behind (a long stall); resynchronise rather than
                # trying to replay the whole backlog.
                self._sequence_next_time = now + frame_period

            self._ticks = frame
            return frame

    def _send_pose_packet(self, snap=False, max_step=None):
        with self._lock:
            ticks = list(self._ticks)
            max_step = max_step or self._max_step
            self._seq += 1
            seq = self._seq

        flags = POSE_FLAG_SNAP if snap else 0
        packet = struct.pack(_FMT_POSE, MAGIC_POSE, flags, max_step, seq, *ticks)
        return self._send(packet)

    def _send_session(self, action):
        with self._lock:
            self._seq += 1
            seq = self._seq
        return self._send(struct.pack(_FMT_SESSION, MAGIC_SESSION, action, seq))

    def _send(self, packet):
        with self._lock:
            sock = self._socket
            # An HTTP port on the address is for the web routes only.
            host, _ = split_address(self._ip)
            if sock is None:
                return False

        try:
            sock.sendto(packet, (host, self._udp_port))
        except OSError as error:
            with self._lock:
                self._last_error = str(error)
            return False

        with self._lock:
            self._packets_sent += 1
            self._last_error = None
        return True

    # ------------------------------------------------------------ heartbeat

    def _start_thread(self):
        if self._thread is not None and self._thread.is_alive():
            return
        self._stop_event.clear()
        self._thread = threading.Thread(
            target=self._stream_loop, name="robot-link-stream", daemon=True
        )
        self._thread.start()

    def _stop_thread(self):
        self._stop_event.set()
        thread = self._thread
        if thread is not None and thread.is_alive():
            thread.join(timeout=1.0)
        self._thread = None

    def _stream_loop(self):
        period = 1.0 / ROBOT_STREAM_HZ
        ping_period = 1.0 / ROBOT_PING_HZ
        next_ping = 0.0

        while not self._stop_event.wait(period):
            if not self.connected:
                continue

            self._expire_drive()

            if not self.streaming:
                # Keeps the firmware's real-time session from timing out while
                # the operator is not moving anything. Rate-limited separately,
                # since holding a pose does not need the full stream rate. Any
                # packet also feeds the firmware's LUT failsafe, so this is what
                # keeps a native gait walking as well.
                now = time.monotonic()
                if now >= next_ping:
                    self._send_session(RT_PING)
                    next_ping = now + ping_period
                continue

            with self._lock:
                playing_sequence = self._sequence is not None

            if playing_sequence:
                # Gait frames are small deltas designed to be played back to
                # back, so the slew limit is relaxed for them; otherwise the
                # robot lags behind the gait instead of walking it.
                if self._advance_sequence() is not None:
                    self._send_pose_packet(max_step=ROBOT_SEQUENCE_MAX_STEP)
            else:
                self._send_pose_packet()


# Single link shared by every Dash callback in the process.
ROBOT_LINK = RobotLink()
