# Real-time link between the simulator and the physical ESP32 hexapod.
#
# The simulator and the robot describe a leg pose with different conventions.
# The simulator uses alpha/beta/gamma (see hexapod/linkage.py); the robot's
# firmware stores raw servo ticks generated by path_tool's inverse_kinematics,
# which produces servo angles j1/j2/j3 in the range [0, 180] where 90 is the
# servo's mid position.
#
# The relationship, verified against path_tool by round-tripping foot-tip
# positions, is:
#
#     j1 = 90 + alpha                    (all legs)
#     j2 = 90 - beta   right legs        j2 = 90 + beta   left legs
#     j3 = 90 + gamma  right legs        j3 = 90 - gamma  left legs
#
# and a servo angle becomes a tick with
#
#     ticks = round(j / 180 * (SERVO_MAX - SERVO_MIN) + SERVO_MIN)
#
# which maps j=90 to 307, matching SERVOMID in the firmware's config.h.
#
# Leg order is the same on both sides (right front/middle/back, then left
# front/middle/back), so no reordering is needed.

import socket
import struct
import threading
import time

from settings import (
    ROBOT_UDP_PORT,
    ROBOT_STREAM_HZ,
    ROBOT_PING_HZ,
    ROBOT_DEFAULT_MAX_STEP,
    ROBOT_SEQUENCE_MAX_STEP,
)
from hexapod.robot_profiles import (
    DEFAULT_PROFILE,
    get_joint_limits,
    get_profile,
    get_sequence_fps,
)

# Servo tick range, mirrors SERVOMIN/SERVOMAX in the firmware's config.h
SERVO_MIN_TICKS = 102
SERVO_MID_TICKS = 307
SERVO_MAX_TICKS = 512
_TICKS_PER_DEGREE = (SERVO_MAX_TICKS - SERVO_MIN_TICKS) / 180.0

# Packet magics, mirrors hexapod_esp32.ino
MAGIC_MOTION = 0xA5
MAGIC_POSE = 0xA6
MAGIC_SESSION = 0xA7

POSE_FLAG_SNAP = 0x01

# Session actions
RT_EXIT = 0
RT_ENTER = 1
RT_RELAX = 2
RT_PING = 3

# struct formats. '<' keeps these little-endian and unpadded, matching the
# firmware's #pragma pack(1) structs (6 / 44 / 6 bytes).
_FMT_MOTION = "<BBI"
_FMT_POSE = "<BBHI" + "h" * 18
_FMT_SESSION = "<BBI"

# +1 for right legs (ids 0-2), -1 for left legs (ids 3-5)
LEG_SIGN = (1, 1, 1, -1, -1, -1)

# Motion command ids, mirrors the RobotCommand enum in the firmware
MOTION_COMMANDS = {
    "standby": 0,
    "walk_0": 1,
    "walk_180": 2,
    "walk_r45": 3,
    "walk_r90": 4,
    "walk_r135": 5,
    "walk_l45": 6,
    "walk_l90": 7,
    "walk_l135": 8,
    "fast_forward": 9,
    "fast_backward": 10,
    "turn_left": 11,
    "turn_right": 12,
    "climb_forward": 13,
    "climb_backward": 14,
    "rotate_x": 15,
    "rotate_y": 16,
    "rotate_z": 17,
    "twist": 18,
}


def joint_angles_to_servo_angles(leg_id, coxia, femur, tibia):
    """Convert one leg's simulator angles to the robot's j1/j2/j3 servo angles."""
    sign = LEG_SIGN[leg_id]
    return (
        90.0 + coxia,
        90.0 - sign * femur,
        90.0 + sign * tibia,
    )


def servo_angle_to_ticks(angle):
    """Convert a servo angle in degrees to a PWM tick count, clamped to range."""
    ticks = round(angle * _TICKS_PER_DEGREE + SERVO_MIN_TICKS)
    return int(min(max(ticks, SERVO_MIN_TICKS), SERVO_MAX_TICKS))


def clamp_pose_angles(coxia, femur, tibia, profile_name=DEFAULT_PROFILE):
    """Clamp simulator angles to the robot's mechanically safe joint range.

    The simulator permits far more travel than the hardware has (beta and gamma
    go to +/-180 there), so this is what keeps an unreachable simulator pose
    from being sent to the servos as a hard stop.
    """
    limits = get_joint_limits(profile_name)
    return (
        min(max(coxia, -limits["coxia"]), limits["coxia"]),
        min(max(femur, -limits["femur"]), limits["femur"]),
        min(max(tibia, -limits["tibia"]), limits["tibia"]),
    )


def pose_to_ticks(poses, profile_name=DEFAULT_PROFILE):
    """Convert a simulator pose dict to a flat list of 18 servo ticks.

    `poses` is the structure used throughout the simulator: keys 0-5 (int or
    str) mapping to dicts with "coxia", "femur" and "tibia" in degrees.
    Returns ticks ordered leg-major, matching the firmware's LUT layout.

    The angle-to-tick relation is the same for both robots; only the joint
    travel limits are profile-specific.
    """
    ticks = []
    for leg_id in range(6):
        pose = poses.get(leg_id, poses.get(str(leg_id)))
        if pose is None:
            coxia = femur = tibia = 0.0
        else:
            coxia = pose.get("coxia") or 0.0
            femur = pose.get("femur") or 0.0
            tibia = pose.get("tibia") or 0.0

        coxia, femur, tibia = clamp_pose_angles(coxia, femur, tibia, profile_name)
        for angle in joint_angles_to_servo_angles(leg_id, coxia, femur, tibia):
            ticks.append(servo_angle_to_ticks(angle))

    return ticks


# Standby posture, decoded from the firmware's lut_standby ({307, 239, 273} for
# the right legs). Both robots bake standby from gen_posture(60, 75), whose
# joint angles do not depend on link lengths, so this is shared.
STANDBY_POSE = {
    leg_id: {
        "id": leg_id,
        "coxia": 0.0,
        "femur": 30.0,
        "tibia": -15.0,
    }
    for leg_id in range(6)
}


class RobotLink:
    """UDP client that streams simulator poses to the hexapod.

    A background thread republishes the most recent pose at a steady rate. That
    matters because Dash only runs callbacks when the user interacts, while the
    firmware drops out of real-time mode if it stops hearing from us. The thread
    keeps the session alive and turns sporadic UI events into a smooth stream.
    """

    def __init__(self):
        self._lock = threading.Lock()
        self._socket = None
        self._thread = None
        self._stop_event = threading.Event()

        self._profile_name = DEFAULT_PROFILE
        self._ip = get_profile(DEFAULT_PROFILE)["ip"]
        self._connected = False
        self._streaming = False
        self._max_step = ROBOT_DEFAULT_MAX_STEP
        self._ticks = pose_to_ticks(STANDBY_POSE, DEFAULT_PROFILE)
        self._seq = 0
        self._packets_sent = 0
        self._last_error = None
        self._last_sent_time = 0.0

        # Gait sequence playback, driven by the stream thread
        self._sequence = None
        self._sequence_index = 0
        self._sequence_loop = True
        self._sequence_next_time = 0.0
        self._sequence_fps = get_sequence_fps(DEFAULT_PROFILE)

    # ---------------------------------------------------------------- status

    @property
    def connected(self):
        with self._lock:
            return self._connected

    @property
    def streaming(self):
        with self._lock:
            return self._streaming

    @property
    def profile_name(self):
        with self._lock:
            return self._profile_name

    def status(self):
        with self._lock:
            return {
                "connected": self._connected,
                "streaming": self._streaming,
                "ip": self._ip,
                "packets_sent": self._packets_sent,
                "last_error": self._last_error,
                "max_step": self._max_step,
                "profile": self._profile_name,
                "label": get_profile(self._profile_name)["label"],
            }

    def set_profile(self, profile_name):
        """Select which physical robot is being driven.

        Switching robots while connected would keep streaming poses clamped for
        the previous machine, so the session is closed first.
        """
        if profile_name == self.profile_name:
            return

        if self.connected:
            self.disconnect()

        with self._lock:
            self._profile_name = profile_name
            self._ip = get_profile(profile_name)["ip"]
            self._sequence_fps = get_sequence_fps(profile_name)
            self._sequence = None
            self._sequence_index = 0
            self._ticks = pose_to_ticks(STANDBY_POSE, profile_name)

    # ------------------------------------------------------------ connection

    def connect(self, ip=None):
        """Open the socket and put the robot into real-time mode."""
        with self._lock:
            if ip:
                self._ip = ip
            if self._socket is None:
                try:
                    self._socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                    self._socket.setblocking(False)
                except OSError as error:
                    self._last_error = str(error)
                    return False
            self._connected = True
            self._last_error = None

        self._send_session(RT_ENTER)
        self._start_thread()
        return True

    def disconnect(self):
        """Return the robot to LUT control and close the socket."""
        self._send_session(RT_EXIT)
        self._stop_thread()

        with self._lock:
            self._connected = False
            self._streaming = False
            self._sequence = None
            self._sequence_index = 0
            if self._socket is not None:
                self._socket.close()
                self._socket = None

    def relax(self):
        """Cut PWM drive so the servos go limp. Also stops streaming."""
        self._send_session(RT_RELAX)
        with self._lock:
            self._streaming = False

    def set_ip(self, ip):
        with self._lock:
            self._ip = ip

    def set_max_step(self, max_step):
        with self._lock:
            self._max_step = max(1, int(max_step))

    def set_streaming(self, streaming):
        with self._lock:
            self._streaming = bool(streaming) and self._connected

    # --------------------------------------------------------------- sending

    def send_pose(self, poses, snap=False):
        """Set the pose that will be streamed to the robot.

        Posing by hand takes precedence over any gait sequence in flight.
        """
        ticks = pose_to_ticks(poses, self.profile_name)
        with self._lock:
            self._ticks = ticks
            self._sequence = None
            self._sequence_index = 0
        if self.streaming:
            self._send_pose_packet(snap=snap)

    def send_motion_command(self, motion_name):
        """Ask the robot to run one of its own built-in gait LUTs.

        Preferred over streaming for the pre-programmed motions: the ESP32 plays
        the gait from flash, so smoothness does not depend on WiFi latency.
        """
        command_id = MOTION_COMMANDS.get(motion_name)
        if command_id is None:
            return False

        # Streaming and LUT playback are mutually exclusive on the robot: the
        # firmware leaves real-time mode as soon as it sees a motion command.
        with self._lock:
            self._streaming = False
            self._sequence = None
            self._sequence_index = 0
            self._seq += 1
            seq = self._seq
        return self._send(struct.pack(_FMT_MOTION, MAGIC_MOTION, command_id, seq))

    def play_sequence(self, pose_frames, loop=True, fps=None):
        """Stream a list of poses as a gait, timed by the stream thread.

        Driving frames from Dash callbacks would tie gait timing to browser
        round-trips; doing it here keeps the cadence steady. Prefer
        send_motion_command() for the robot's built-in gaits, which avoids the
        network being in the loop at all.
        """
        profile_name = self.profile_name
        frames = [pose_to_ticks(pose, profile_name) for pose in pose_frames]
        if not frames:
            return False

        with self._lock:
            self._sequence = frames
            self._sequence_index = 0
            self._sequence_loop = loop
            self._sequence_fps = fps or get_sequence_fps(profile_name)
            self._sequence_next_time = 0.0
            self._streaming = self._connected
        return True

    def stop_sequence(self):
        """Stop gait playback and hold the last frame."""
        with self._lock:
            self._sequence = None
            self._sequence_index = 0

    def _advance_sequence(self):
        """Return the frame that is due now, else None.

        If the thread woke late (Windows timer granularity is ~15 ms, coarser
        than a 12 ms gait frame) this skips the frames that fell due in the
        meantime rather than emitting them all late, so the gait keeps correct
        wall-clock timing instead of drifting slower and slower.
        """
        now = time.monotonic()
        with self._lock:
            if not self._sequence:
                return None

            if now < self._sequence_next_time:
                return None

            frame_period = 1.0 / self._sequence_fps

            if self._sequence_next_time == 0.0:
                # First frame of a new sequence.
                self._sequence_next_time = now
                overdue = 1
            else:
                overdue = int((now - self._sequence_next_time) / frame_period) + 1

            frame = None
            for _ in range(overdue):
                frame = self._sequence[self._sequence_index]
                self._sequence_index += 1

                if self._sequence_index >= len(self._sequence):
                    if self._sequence_loop:
                        self._sequence_index = 0
                    else:
                        self._sequence = None
                        self._sequence_index = 0
                        break

            # Advance the schedule by whole frame periods from when the frame
            # was *due*, not from when this thread happened to wake. Resetting
            # from `now` would fold the wake-up lateness into every frame and
            # the gait would run progressively slower than on the robot.
            self._sequence_next_time += overdue * frame_period
            if self._sequence_next_time <= now:
                # Fell far behind (a long stall); resynchronise rather than
                # trying to replay the whole backlog.
                self._sequence_next_time = now + frame_period

            self._ticks = frame
            return frame

    def _send_pose_packet(self, snap=False, max_step=None):
        with self._lock:
            ticks = list(self._ticks)
            max_step = max_step or self._max_step
            self._seq += 1
            seq = self._seq

        flags = POSE_FLAG_SNAP if snap else 0
        packet = struct.pack(_FMT_POSE, MAGIC_POSE, flags, max_step, seq, *ticks)
        return self._send(packet)

    def _send_session(self, action):
        with self._lock:
            self._seq += 1
            seq = self._seq
        return self._send(struct.pack(_FMT_SESSION, MAGIC_SESSION, action, seq))

    def _send(self, packet):
        with self._lock:
            sock = self._socket
            ip = self._ip
            if sock is None:
                return False

        try:
            sock.sendto(packet, (ip, ROBOT_UDP_PORT))
        except OSError as error:
            with self._lock:
                self._last_error = str(error)
            return False

        with self._lock:
            self._packets_sent += 1
            self._last_sent_time = time.time()
            self._last_error = None
        return True

    # ------------------------------------------------------------ heartbeat

    def _start_thread(self):
        if self._thread is not None and self._thread.is_alive():
            return
        self._stop_event.clear()
        self._thread = threading.Thread(
            target=self._stream_loop, name="robot-link-stream", daemon=True
        )
        self._thread.start()

    def _stop_thread(self):
        self._stop_event.set()
        thread = self._thread
        if thread is not None and thread.is_alive():
            thread.join(timeout=1.0)
        self._thread = None

    def _stream_loop(self):
        period = 1.0 / ROBOT_STREAM_HZ
        ping_period = 1.0 / ROBOT_PING_HZ
        next_ping = 0.0

        while not self._stop_event.wait(period):
            if not self.connected:
                continue

            if not self.streaming:
                # Keeps the firmware's real-time session from timing out while
                # the operator is not moving anything. Rate-limited separately,
                # since holding a pose does not need the full stream rate.
                now = time.monotonic()
                if now >= next_ping:
                    self._send_session(RT_PING)
                    next_ping = now + ping_period
                continue

            with self._lock:
                playing_sequence = self._sequence is not None

            if playing_sequence:
                # Gait frames are small deltas designed to be played back to
                # back, so the slew limit is relaxed for them; otherwise the
                # robot lags behind the gait instead of walking it.
                if self._advance_sequence() is not None:
                    self._send_pose_packet(max_step=ROBOT_SEQUENCE_MAX_STEP)
            else:
                self._send_pose_packet()


# Single link shared by every Dash callback in the process.
ROBOT_LINK = RobotLink()
