import dash_bootstrap_components as dbc
from dash import dcc, html

from widgets.section_maker import make_slider_field

# --- Element IDs ---
MOTION_DROPDOWN_ID = "motion-type-dropdown"
MOTION_PLAY_BTN_ID = "motion-play-btn"
MOTION_SPEED_SLIDER_ID = "motion-speed-slider"
MOTION_FRAME_SLIDER_ID = "motion-frame-slider"
MOTION_LOOP_CHECKBOX_ID = "motion-loop-checkbox"
MOTION_FRAME_DISPLAY_ID = "motion-frame-display"

# --- Data ---
MOTION_TYPES = [
    {"label": "Standby (reset)", "value": "standby"},
    {"label": "Walk forward", "value": "walk_0"},
    {"label": "Walk backward", "value": "walk_180"},
    {"label": "Walk right 45°", "value": "walk_r45"},
    {"label": "Walk right 90°", "value": "walk_r90"},
    {"label": "Walk right 135°", "value": "walk_r135"},
    {"label": "Walk left 45°", "value": "walk_l45"},
    {"label": "Walk left 90°", "value": "walk_l90"},
    {"label": "Walk left 135°", "value": "walk_l135"},
    {"label": "Fast forward", "value": "fast_forward"},
    {"label": "Fast backward", "value": "fast_backward"},
    {"label": "Turn left", "value": "turn_left"},
    {"label": "Turn right", "value": "turn_right"},
    {"label": "Climb forward", "value": "climb_forward"},
    {"label": "Climb backward", "value": "climb_backward"},
    {"label": "Rotate X (pitch)", "value": "rotate_x"},
    {"label": "Rotate Y (roll)", "value": "rotate_y"},
    {"label": "Rotate Z (wobble)", "value": "rotate_z"},
    {"label": "Twist (figure-8)", "value": "twist"},
    {"label": "Stand up", "value": "standup"},
]

# --- UI Components ---
def make_section(header, content, blurb=None):
    body = [html.H6(header, className="mb-2" if blurb else "mb-3")]
    if blurb:
        body.append(html.P(blurb, className="text-muted small mb-3"))
    body.append(content)
    return dbc.Card(dbc.CardBody(body), className="mb-3 ind-card")


dropdown = dbc.Select(
    id=MOTION_DROPDOWN_ID,
    options=MOTION_TYPES,
    value="walk_0",
)

# Play takes the full width; the frame counter and the loop toggle share the
# line under it, so nothing has to wrap however narrow the panel is.
playback_controls = html.Div(
    [
        dbc.Button(
            "▶ Play",
            id=MOTION_PLAY_BTN_ID,
            color="primary",
            className="w-100 fw-bold mb-2",
        ),
        html.Div(
            [
                html.Div(
                    "Frame 0/0",
                    id=MOTION_FRAME_DISPLAY_ID,
                    className="fw-bold font-monospace",
                ),
                dcc.Checklist(
                    id=MOTION_LOOP_CHECKBOX_ID,
                    options=[{"label": " Loop", "value": "loop"}],
                    value=["loop"],
                    className="fw-bold",
                ),
            ],
            className="d-flex justify-content-between align-items-center",
        ),
    ],
    className="mb-3",
)

speed_slider = make_slider_field(
    MOTION_SPEED_SLIDER_ID,
    "Playback speed (×)",
    0.2,
    3.0,
    0.1,
    1.0,
    marks={0.5: "0.5x", 1.0: "1x", 2.0: "2x", 3.0: "3x"},
)

frame_scrubber = make_slider_field(
    MOTION_FRAME_SLIDER_ID,
    "Frame",
    0,
    27,  # Updated with the selected motion
    1,
    0,
)

# --- Put it together ---
# Driving the physical robot is not here on purpose: those controls live in the
# global panel (widgets/robot_link_ui.py) so they are reachable from every page.
MOTION_WIDGETS_SECTION = html.Div(
    [
        make_section(
            "Motion animations",
            dropdown,
            blurb="Select and play predefined hexapod motions generated by the path tool.",
        ),
        make_section(
            "Playback",
            html.Div([playback_controls, speed_slider, frame_scrubber]),
        ),
    ]
)
