import json
import copy
from dash.dependencies import Input, Output, State
from dash import dcc, html, no_update
from dash.exceptions import PreventUpdate
import dash

from app import app
from hexapod.models import VirtualHexapod
from hexapod.const import BASE_PLOTTER, BASE_DIMENSIONS, BASE_FIGURE
from widgets.motion_ui import (
    MOTION_WIDGETS_SECTION,
    MOTION_DROPDOWN_ID,
    MOTION_PLAY_BTN_ID,
    MOTION_SPEED_SLIDER_ID,
    MOTION_FRAME_SLIDER_ID,
    MOTION_LOOP_CHECKBOX_ID,
    MOTION_FRAME_DISPLAY_ID,
)
from pages import helpers, shared
from hexapod.path_generator import generate_poses

# --- Page Layout Elements ---
INTERVAL_ID = "motion-interval"
ANIMATION_STORE_ID = "motion-figures-store"
PLAY_STATE_STORE_ID = "play-state-store"
GRAPH_ID = "motion-graph"

hidden_components = html.Div([
    dcc.Interval(id=INTERVAL_ID, interval=50, n_intervals=0, disabled=True),
    dcc.Store(id=ANIMATION_STORE_ID, data=[]),
    dcc.Store(id=PLAY_STATE_STORE_ID, data=False),
])

motion_widgets = html.Div([
    html.H5("Motion Animations", className="fw-bold mb-3 text-center"),
    html.P("Select and play predefined hexapod motions generated by the path tool.", className="text-muted small mb-4"),
    MOTION_WIDGETS_SECTION,
    hidden_components
])

sidebar = shared.make_standard_page_sidebar(
    message_section_id="motion-message-section",
    params_hidden_section_id="motion-hidden-section",
    params_widgets_section=motion_widgets
)

layout = shared.make_standard_page_layout(GRAPH_ID, sidebar)

# --- Callbacks ---

# 1. Server-side: Generate pre-rendered figures for smooth client-side playback
@app.callback(
    Output(ANIMATION_STORE_ID, "data"),
    Output(MOTION_FRAME_SLIDER_ID, "max"),
    Output(MOTION_FRAME_SLIDER_ID, "marks"),
    Output(MOTION_FRAME_SLIDER_ID, "value"),
    Output(PLAY_STATE_STORE_ID, "data"),
    Output(MOTION_PLAY_BTN_ID, "children"),
    Output(MOTION_PLAY_BTN_ID, "color"),
    Output(INTERVAL_ID, "disabled"),
    Input(MOTION_DROPDOWN_ID, "value"),
    shared.DIMS_JSON_CALLBACK_INPUT,
)
def update_motion_and_dimensions(motion_name, dimensions_json):
    if not motion_name:
        raise PreventUpdate
        
    dimensions = helpers.load_params(dimensions_json, "dims")
    frames = generate_poses(motion_name)
    max_frames = max(len(frames) - 1, 0)
    marks = {0: "0", max_frames: str(max_frames)}
    
    figures = []
    base_fig = BASE_FIGURE
    for pose in frames:
        hexapod = VirtualHexapod(dimensions)
        try:
            hexapod.update(pose)
        except Exception as e:
            print(f"Pose unstable for frame, skipping update: {e}")
            # Fall back to base posture if unstable
            
        fig_copy = copy.deepcopy(base_fig)
        BASE_PLOTTER.update(fig_copy, hexapod)
        figures.append(fig_copy)
        
    # Reset playback state
    playing = False
    btn_text = "▶ Play"
    btn_color = "primary"
    disabled = True
    current_frame = 0
    
    return figures, max_frames, marks, current_frame, playing, btn_text, btn_color, disabled


# 2. Client-side: Handle Play/Pause button
app.clientside_callback(
    """
    function(n_clicks, is_playing, current_frame, max_frame) {
        if (n_clicks === undefined) {
            return [window.dash_clientside.no_update, window.dash_clientside.no_update, window.dash_clientside.no_update, window.dash_clientside.no_update, window.dash_clientside.no_update];
        }
        let playing = !is_playing;
        let next_frame = current_frame;
        
        // If starting to play and we are at the end, reset to frame 0
        if (playing && current_frame >= max_frame) {
            next_frame = 0;
        }
        
        let btn_text = playing ? "⏸ Pause" : "▶ Play";
        let btn_color = playing ? "danger" : "primary";
        
        return [playing, btn_text, btn_color, !playing, next_frame];
    }
    """,
    Output(PLAY_STATE_STORE_ID, "data", allow_duplicate=True),
    Output(MOTION_PLAY_BTN_ID, "children", allow_duplicate=True),
    Output(MOTION_PLAY_BTN_ID, "color", allow_duplicate=True),
    Output(INTERVAL_ID, "disabled", allow_duplicate=True),
    Output(MOTION_FRAME_SLIDER_ID, "value", allow_duplicate=True),
    Input(MOTION_PLAY_BTN_ID, "n_clicks"),
    State(PLAY_STATE_STORE_ID, "data"),
    State(MOTION_FRAME_SLIDER_ID, "value"),
    State(MOTION_FRAME_SLIDER_ID, "max"),
    prevent_initial_call=True
)

# 3. Client-side: Handle interval ticks
app.clientside_callback(
    """
    function(n_intervals, current_frame, max_frame, loop_values) {
        let loop = loop_values && loop_values.includes("loop");
        let next_frame = current_frame + 1;
        let playing = true;
        
        if (next_frame > max_frame) {
            if (loop) {
                next_frame = 0;
            } else {
                next_frame = max_frame;
                playing = false;
            }
        }
        
        if (!playing) {
            return [next_frame, false, "▶ Play", "primary", true];
        } else {
            return [next_frame, window.dash_clientside.no_update, window.dash_clientside.no_update, window.dash_clientside.no_update, window.dash_clientside.no_update];
        }
    }
    """,
    Output(MOTION_FRAME_SLIDER_ID, "value", allow_duplicate=True),
    Output(PLAY_STATE_STORE_ID, "data", allow_duplicate=True),
    Output(MOTION_PLAY_BTN_ID, "children", allow_duplicate=True),
    Output(MOTION_PLAY_BTN_ID, "color", allow_duplicate=True),
    Output(INTERVAL_ID, "disabled", allow_duplicate=True),
    Input(INTERVAL_ID, "n_intervals"),
    State(MOTION_FRAME_SLIDER_ID, "value"),
    State(MOTION_FRAME_SLIDER_ID, "max"),
    State(MOTION_LOOP_CHECKBOX_ID, "value"),
    prevent_initial_call=True
)

# 4. Client-side: Sync slider with graph frame
app.clientside_callback(
    """
    function(frame_idx, figures, relayoutData, current_fig) {
        if (frame_idx === undefined || !figures || figures.length === 0) {
            return [window.dash_clientside.no_update, window.dash_clientside.no_update];
        }
        if (frame_idx >= figures.length) {
            frame_idx = 0;
        }
        
        // Clone the figure object to avoid mutating the original store copy
        let new_fig = JSON.parse(JSON.stringify(figures[frame_idx]));
        
        // Preserve user camera view interaction seamlessly
        let camera = null;
        if (relayoutData && relayoutData['scene.camera']) {
            camera = relayoutData['scene.camera'];
        } else if (current_fig && current_fig.layout && current_fig.layout.scene && current_fig.layout.scene.camera) {
            camera = current_fig.layout.scene.camera;
        }
        
        if (camera && new_fig.layout && new_fig.layout.scene) {
            new_fig.layout.scene.camera = camera;
        }
        
        let display = `Frame ${frame_idx}/${figures.length - 1}`;
        return [new_fig, display];
    }
    """,
    Output(GRAPH_ID, "figure"),
    Output(MOTION_FRAME_DISPLAY_ID, "children"),
    Input(MOTION_FRAME_SLIDER_ID, "value"),
    State(ANIMATION_STORE_ID, "data"),
    State(GRAPH_ID, "relayoutData"),
    State(GRAPH_ID, "figure"),
)

# 5. Client-side: Control interval speed
app.clientside_callback(
    """
    function(speed) {
        let base = 50;
        let s = speed > 0.1 ? speed : 0.1;
        return parseInt(base / s);
    }
    """,
    Output(INTERVAL_ID, "interval"),
    Input(MOTION_SPEED_SLIDER_ID, "value"),
    prevent_initial_call=True
)
