import copy
from dash.dependencies import Input, Output, State
from dash import dcc, html, no_update
from dash.exceptions import PreventUpdate

from app import app
from hexapod.models import VirtualHexapod
from hexapod.const import BASE_PLOTTER, BASE_FIGURE
from widgets.motion_ui import (
    MOTION_WIDGETS_SECTION,
    MOTION_DROPDOWN_ID,
    MOTION_PLAY_BTN_ID,
    MOTION_SPEED_SLIDER_ID,
    MOTION_FRAME_SLIDER_ID,
    MOTION_LOOP_CHECKBOX_ID,
    MOTION_FRAME_DISPLAY_ID,
)
from pages import shared
from hexapod.path_generator import generate_poses
from hexapod.robot_link import ROBOT_LINK, MOTION_COMMANDS
from hexapod.robot_profiles import get_simulator_dimensions
from widgets.robot_link_ui import (
    ROBOT_PROFILE_SELECT_ID,
    ROBOT_MOTION_WIDGETS_SECTION,
    ROBOT_MOTION_MODE_ID,
    ROBOT_MOTION_LOOP_ID,
    ROBOT_MOTION_RUN_BTN_ID,
    ROBOT_MOTION_STOP_BTN_ID,
    ROBOT_MOTION_MESSAGE_ID,
    ROBOT_MOTION_CONTROLS_ID,
    ROBOT_MOTION_POLL_INTERVAL_ID,
    SECTION_CONTROLS_CLASS,
    SECTION_CONTROLS_OFFLINE_CLASS,
)

# --- Page Layout Elements ---
INTERVAL_ID = "motion-interval"
ANIMATION_STORE_ID = "motion-figures-store"
PLAY_STATE_STORE_ID = "play-state-store"
GRAPH_ID = "motion-graph"

hidden_components = html.Div([
    dcc.Interval(id=INTERVAL_ID, interval=50, n_intervals=0, disabled=True),
    dcc.Store(id=ANIMATION_STORE_ID, data=[]),
    dcc.Store(id=PLAY_STATE_STORE_ID, data=False),
])

motion_widgets = html.Div([
    html.H5("Motion Animations", className="fw-bold mb-3 text-center"),
    html.P("Select and play predefined hexapod motions generated by the path tool.", className="text-muted small mb-4"),
    MOTION_WIDGETS_SECTION,
    # Running a gait on the hardware needs a motion to name, and this is the
    # only page that has one, so the controls for it sit under the dropdown
    # that chooses it rather than in the global panel.
    ROBOT_MOTION_WIDGETS_SECTION,
    hidden_components
])

sidebar = shared.make_standard_page_sidebar(
    message_section_id="motion-message-section",
    params_hidden_section_id="motion-hidden-section",
    params_widgets_section=motion_widgets
)

layout = shared.make_standard_page_layout(GRAPH_ID, sidebar)

# --- Callbacks ---

# 1. Server-side: Generate pre-rendered figures for smooth client-side playback
@app.callback(
    Output(ANIMATION_STORE_ID, "data"),
    Output(MOTION_FRAME_SLIDER_ID, "max"),
    Output(MOTION_FRAME_SLIDER_ID, "marks"),
    Output(MOTION_FRAME_SLIDER_ID, "value"),
    Output(PLAY_STATE_STORE_ID, "data"),
    Output(MOTION_PLAY_BTN_ID, "children"),
    Output(MOTION_PLAY_BTN_ID, "color"),
    Output(INTERVAL_ID, "disabled"),
    Input(MOTION_DROPDOWN_ID, "value"),
    Input(ROBOT_PROFILE_SELECT_ID, "value"),
)
def update_motion_and_dimensions(motion_name, profile_name):
    if not motion_name:
        raise PreventUpdate

    # The body is measured from the profile, not from the dimension widgets.
    # These motions are baked joint angles, solved by generate_poses against one
    # robot's leg lengths and mount angles, and they only describe a walk on that
    # geometry -- replay them on a body of another shape and the legs land
    # somewhere the gait never intended, which tears the support polygon apart as
    # the animation plays.
    dimensions = get_simulator_dimensions(profile_name)
    frames = generate_poses(motion_name, profile_name)
    max_frames = max(len(frames) - 1, 0)
    marks = {0: "0", max_frames: str(max_frames)}

    figures = []
    base_fig = BASE_FIGURE
    for pose in frames:
        hexapod = VirtualHexapod(dimensions)
        try:
            hexapod.update(pose)
        except Exception as e:
            print(f"Pose unstable for frame, skipping update: {e}")
            # Fall back to base posture if unstable
            
        fig_copy = copy.deepcopy(base_fig)
        BASE_PLOTTER.update(fig_copy, hexapod)
        figures.append(fig_copy)
        
    # Reset playback state
    playing = False
    btn_text = "▶ Play"
    btn_color = "primary"
    disabled = True
    current_frame = 0
    
    return figures, max_frames, marks, current_frame, playing, btn_text, btn_color, disabled


# 2. Client-side: Handle Play/Pause button
app.clientside_callback(
    """
    function(n_clicks, is_playing, current_frame, max_frame) {
        if (n_clicks === undefined) {
            return [window.dash_clientside.no_update, window.dash_clientside.no_update, window.dash_clientside.no_update, window.dash_clientside.no_update, window.dash_clientside.no_update];
        }
        let playing = !is_playing;
        let next_frame = current_frame;
        
        // If starting to play and we are at the end, reset to frame 0
        if (playing && current_frame >= max_frame) {
            next_frame = 0;
        }
        
        let btn_text = playing ? "⏸ Pause" : "▶ Play";
        let btn_color = playing ? "danger" : "primary";
        
        return [playing, btn_text, btn_color, !playing, next_frame];
    }
    """,
    Output(PLAY_STATE_STORE_ID, "data", allow_duplicate=True),
    Output(MOTION_PLAY_BTN_ID, "children", allow_duplicate=True),
    Output(MOTION_PLAY_BTN_ID, "color", allow_duplicate=True),
    Output(INTERVAL_ID, "disabled", allow_duplicate=True),
    Output(MOTION_FRAME_SLIDER_ID, "value", allow_duplicate=True),
    Input(MOTION_PLAY_BTN_ID, "n_clicks"),
    State(PLAY_STATE_STORE_ID, "data"),
    State(MOTION_FRAME_SLIDER_ID, "value"),
    State(MOTION_FRAME_SLIDER_ID, "max"),
    prevent_initial_call=True
)

# 3. Client-side: Handle interval ticks
app.clientside_callback(
    """
    function(n_intervals, current_frame, max_frame, loop_values) {
        let loop = loop_values && loop_values.includes("loop");
        let next_frame = current_frame + 1;
        let playing = true;
        
        if (next_frame > max_frame) {
            if (loop) {
                next_frame = 0;
            } else {
                next_frame = max_frame;
                playing = false;
            }
        }
        
        if (!playing) {
            return [next_frame, false, "▶ Play", "primary", true];
        } else {
            return [next_frame, window.dash_clientside.no_update, window.dash_clientside.no_update, window.dash_clientside.no_update, window.dash_clientside.no_update];
        }
    }
    """,
    Output(MOTION_FRAME_SLIDER_ID, "value", allow_duplicate=True),
    Output(PLAY_STATE_STORE_ID, "data", allow_duplicate=True),
    Output(MOTION_PLAY_BTN_ID, "children", allow_duplicate=True),
    Output(MOTION_PLAY_BTN_ID, "color", allow_duplicate=True),
    Output(INTERVAL_ID, "disabled", allow_duplicate=True),
    Input(INTERVAL_ID, "n_intervals"),
    State(MOTION_FRAME_SLIDER_ID, "value"),
    State(MOTION_FRAME_SLIDER_ID, "max"),
    State(MOTION_LOOP_CHECKBOX_ID, "value"),
    prevent_initial_call=True
)

# 4. Client-side: Sync slider with graph frame
app.clientside_callback(
    """
    function(frame_idx, figures, relayoutData, current_fig) {
        if (frame_idx === undefined || !figures || figures.length === 0) {
            return [window.dash_clientside.no_update, window.dash_clientside.no_update];
        }
        if (frame_idx >= figures.length) {
            frame_idx = 0;
        }
        
        // Clone the figure object to avoid mutating the original store copy
        let new_fig = JSON.parse(JSON.stringify(figures[frame_idx]));
        
        // Preserve user camera view interaction seamlessly
        let camera = null;
        if (relayoutData && relayoutData['scene.camera']) {
            camera = relayoutData['scene.camera'];
        } else if (current_fig && current_fig.layout && current_fig.layout.scene && current_fig.layout.scene.camera) {
            camera = current_fig.layout.scene.camera;
        }
        
        if (camera && new_fig.layout && new_fig.layout.scene) {
            new_fig.layout.scene.camera = camera;
        }
        
        let display = `Frame ${frame_idx}/${figures.length - 1}`;
        return [new_fig, display];
    }
    """,
    Output(GRAPH_ID, "figure"),
    Output(MOTION_FRAME_DISPLAY_ID, "children"),
    Input(MOTION_FRAME_SLIDER_ID, "value"),
    State(ANIMATION_STORE_ID, "data"),
    State(GRAPH_ID, "relayoutData"),
    State(GRAPH_ID, "figure"),
)

# 5. Server-side: run the selected motion on the physical robot
# The motion is whatever the dropdown above is previewing, so there is no second
# list to keep in step; nothing is sent until the Run button is pressed.
@app.callback(
    Output(ROBOT_MOTION_MESSAGE_ID, "children"),
    Input(ROBOT_MOTION_RUN_BTN_ID, "n_clicks"),
    State(MOTION_DROPDOWN_ID, "value"),
    State(ROBOT_MOTION_MODE_ID, "value"),
    State(ROBOT_MOTION_LOOP_ID, "value"),
    State(ROBOT_PROFILE_SELECT_ID, "value"),
    prevent_initial_call=True,
)
def run_motion_on_robot(_n_clicks, motion_name, mode, loop_values, profile_name):
    if not ROBOT_LINK.connected:
        return "Not connected — connect in the ROBOT panel first."

    loop = bool(loop_values) and "loop" in loop_values

    if mode == "native":
        if motion_name not in MOTION_COMMANDS:
            # "standup" is the firmware's boot sequence, not a motion LUT it
            # can be commanded into.
            return (
                f"'{motion_name}' has no built-in equivalent on the robot. "
                "Use 'Stream frames from simulator' instead."
            )
        if ROBOT_LINK.send_motion_command(motion_name):
            return f"Robot running its own '{motion_name}' gait."
        return "Failed to send motion command."

    frames = generate_poses(motion_name, profile_name)
    if not ROBOT_LINK.play_sequence(frames, loop=loop):
        return "Nothing to stream for this motion."
    return f"Streaming '{motion_name}' — {len(frames)} frames{' (looping)' if loop else ''}."


@app.callback(
    Output(ROBOT_MOTION_MESSAGE_ID, "children", allow_duplicate=True),
    Input(ROBOT_MOTION_STOP_BTN_ID, "n_clicks"),
    prevent_initial_call=True,
)
def stop_motion_on_robot(_n_clicks):
    if not ROBOT_LINK.connected:
        return "Not connected."

    ROBOT_LINK.stop_sequence()
    ROBOT_LINK.send_motion_command("standby")
    return "Robot returning to standby."


# 6. Server-side: gate the robot controls on there being a robot
# Nothing here can be sent without an open session, so while the link is down
# the section is greyed out and its buttons disabled, and the message line says
# so instead of leaving the last run's result standing.
OFFLINE_MESSAGE = "Connect a robot to run this on the hardware."


@app.callback(
    Output(ROBOT_MOTION_CONTROLS_ID, "className"),
    Output(ROBOT_MOTION_RUN_BTN_ID, "disabled"),
    Output(ROBOT_MOTION_STOP_BTN_ID, "disabled"),
    Output(ROBOT_MOTION_MESSAGE_ID, "children", allow_duplicate=True),
    Input(ROBOT_MOTION_POLL_INTERVAL_ID, "n_intervals"),
    State(ROBOT_MOTION_MESSAGE_ID, "children"),
    prevent_initial_call=True,
)
def sync_robot_motion_controls(_n_intervals, message):
    offline = not ROBOT_LINK.connected

    # The message line is otherwise owned by the run and stop callbacks, so it
    # is only written here when it actually has to change: put the hint up on
    # going offline, take it down on connecting, and leave whatever the last
    # run reported alone the rest of the time.
    if offline:
        new_message = no_update if message == OFFLINE_MESSAGE else OFFLINE_MESSAGE
    else:
        new_message = "" if message == OFFLINE_MESSAGE else no_update

    return (
        SECTION_CONTROLS_OFFLINE_CLASS if offline else SECTION_CONTROLS_CLASS,
        offline,
        offline,
        new_message,
    )


# 6. Client-side: Control interval speed
app.clientside_callback(
    """
    function(speed) {
        let base = 50;
        let s = speed > 0.1 ? speed : 0.1;
        return parseInt(base / s);
    }
    """,
    Output(INTERVAL_ID, "interval"),
    Input(MOTION_SPEED_SLIDER_ID, "value"),
    prevent_initial_call=True
)
